name: Advent of Code

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Cache SBT
      uses: actions/cache@v2
      with:
        path: ~/.sbt/boot
        key: ${{ runner.os }}-sbt-${{ hashFiles('adventofcode/scala/project/build.properties') }}
    - name: Cache Coursier
      uses: actions/cache@v2
      with:
        path: ~/.cache/coursier/v1
        key: ${{ runner.os }}-sbt-${{ hashFiles('adventofcode/scala/build.sbt') }}
    - name: Run tests
      run: |
        sbt test
      working-directory: adventofcode/scala
