name: Advent of Code

on:
  push:
    branches: [ main ]
    paths:
      - 'adventofcode/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'adventofcode/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '17'
    - uses: coursier/cache-action@v6
      with:
        root: adventofcode
    - name: Run tests
      run: sbt scalafmtCheckAll test
      working-directory: adventofcode/scala
