name: Castaway Island

on:
  push:
    branches: [ main ]
    paths:
      - 'castaway-island/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'castaway-island/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '18'
      - uses: coursier/cache-action@v6
        with:
          root: castaway-island
      - run: sbt scalafmtCheckAll test
        working-directory: castaway-island
