name: Cats effect experiments

on:
  push:
    branches: [ main ]
    paths:
      - 'cats-effect-experiments/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'cats-effect-experiments/**'

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      cassandra:
        image: cassandra
        ports:
          - 9042

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: coursier/cache-action@v6
        with:
          root: cats-effect-experiments
      - run: sbt scalafmtCheckAll test
        working-directory: cats-effect-experiments
