name: Cats effect experiments

on:
  push:
    branches: [ main ]
    paths:
      - 'cats-effect-experiments/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'cats-effect-experiments/**'

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      cassandra:
        image: cassandra
        ports:
          - 9042:9042

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          cache: 'sbt'
          distribution: 'temurin'
          java-version: '21'
      - run: sbt scalafmtCheckAll test
        working-directory: cats-effect-experiments
