name: codingame

on:
  push:
    branches: [ main ]
    paths:
      - 'codingame/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'codingame/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - uses: coursier/cache-action@v6
      with:
        root: codingame
    - name: Run tests
      run: sbt scalafmtCheckAll test
      working-directory: codingame
