name: foo-bar-qix

on:
  push:
    branches: [ "main" ]
    paths:
      - 'foo-bar-qix/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'foo-bar-qix/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - run: mvn --batch-mode package --file foo-bar-qix/pom.xml
