name: Function reuse

on:
  push:
    branches: [ main ]
    paths:
      - 'function-reuse/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'function-reuse/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'sbt'
      - run: sbt scalafmtCheckAll test
        working-directory: function-reuse
