name: gilded-rose 

on:
  push:
    branches: [ "main" ]
    paths:
      - 'gilded-rose/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'gilded-rose/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - run: mvn --batch-mode package --file gilded-rose/pom.xml
