name: gilded-rose 

on:
  push:
    branches: [ "main" ]
    paths:
      - 'gilded-rose/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'gilded-rose/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          cache: maven
      - run: mvn --batch-mode package --file gilded-rose/pom.xml

