name: Mow it now

on:
  push:
    branches: [ "main" ]
    paths:
      - 'mowitnow/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'mowitnow/**'

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'sbt'
      - run: sbt scalafmtCheckAll test
        working-directory: mowitnow
