name: Object Mother Scala

on:
  push:
    branches: [ main ]
    paths:
      - 'object-mother/scala/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'object-mother/scala/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
      - uses: coursier/cache-action@v6
        with:
          root: 'object-mother/scala'
      - run: sbt scalafmtCheckAll test
        working-directory: object-mother/scala
