name: Object Mother Java

on:
  push:
    branches: [ main ]
    paths:
      - 'object-mother/java/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'object-mother/java/**'

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '18'
      - uses: gradle/gradle-build-action@v2.4.2
        with:
          arguments: build
          build-root-directory: object-mother/java
