name: Tom Swift Under the Milkwood

on:
  push:
    branches: [ "main" ]
    paths:
      - 'tom-swift-under-the-milkwood/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'tom-swift-under-the-milkwood/**'

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'sbt'
      - run: sbt scalafmtCheckAll test
        working-directory: tom-swift-under-the-milkwood
